name: Java CI

on:
  pull_request:
    branches: [ "dev", "main" ]

# 경로 수정: 프로젝트 루트 사용
defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
          cache-dependency-path: 'build.gradle' # 경로 수정

      - name: Make application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Test with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/*[!plain].jar # 경로 수정
          if-no-files-found: error